# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 05:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import reservation.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('end_date', models.DateTimeField(default=reservation.models.thirty_days_after)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
