# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20180919_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.BigIntegerField(default=reservation.models.get_unix_time),
        ),
    ]
