# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0006_auto_20180919_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.BigIntegerField(default=reservation.models.two_day_later),
        ),
    ]
